### ISSUE TITLE
Uncertainty in BC

### ISSUE THREAD

**Issue by TobyOnGithub** [casaluca/bolometric-corrections#1]
How to calc. an uncertainty in the BC? Is that possible? Maybe from bootstrapping? Is that implemented given uncertainties in Teff, logg, Fe/H and E(B-B)?

**Comment by casaluca** [comment]
The easiest way is to use uncertainties in Teff, logg, Fe/H and E(B-V) to generate a distributions in those parameters for each input star. Then pass this distribution into the input.sample.all, and the bcall script will output a table of BCs for each input combinations of those parameters.
