### ISSUE TITLE
Apply bolometric correction to unreddened photometry

### ISSUE THREAD

**Issue by christopherburke** [casaluca/bolometric-corrections#2]
Hello Dr. Casagrande,
  Thank you for providing this wonderful resource. My question is do I apply the bolometric correction as output from the routines to the original photometry? In other words, I do not need to apply an extinction correction to the observed magnitude before applying the bolometric correction because the output BolCor includes the passband extinction correction.
  In other words
  1)  Mbol = BolCor + mobs - 5*log10(dist[pc]) + 5
  is the correct way to calculate the bolometric magnitude of a star, where BolCor is the output from your routines, mobs is the observed magnitude and dist is the distance to the star in pc.
  versus the incorrect way to calculate 
  2) Mbol = BolCor + mobs - 5*log10(dist[pc]) + 5 - A
  where A is a passband extinction correction.
  
  My reading of the appendix A of Casagrande & Vandenberg (2012) convinces me that equation 1 is correct, but I wanted to double check.

**Comment by casaluca** [comment]
Hi Chris,

Glad to know you find those routines useful! You are correct in your understanding. If you pass an input E(B-V) to those routines, the bolometric correction returned can be applied to the observed magnitude, and no further extinction correction must be applied.

Cheers,
Luca
